!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  auto_exposure_priority: true
  backlight_compensation: true
  brightness: 0
  contrast: 50
  enable_auto_exposure: false
  enable_auto_white_balance: false
  exposure: 190
  frames_queue_size: 24
  gain: 64
  gamma: 300
  global_time_enabled: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      auto_exposure_priority: true
      backlight_compensation: true
      brightness: 0
      contrast: 50
      enable_auto_exposure: false
      enable_auto_white_balance: false
      exposure: 190
      frames_queue_size: 24
      gain: 64
      gamma: 300
      global_time_enabled: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hue: 0
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      power_line_frequency: 1
      saturation: 64
      sharpness: 50
      state: true
      type: ''
      white_balance: 3700.0
    state: []
  hue: 0
  power_line_frequency: 1
  saturation: 64
  sharpness: 50
  white_balance: 3700.0
state: []
